version: '3.3'

services:
  demo_app:
    environment:
      - ALLOWED_HOSTS=appdemo.brayanperera.cyou
    image: 363052508649.dkr.ecr.ap-southeast-1.amazonaws.com/demo-app:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /data/demo_app/db.sqlite3:/code/data/db.sqlite3
