version: '3.3'

services:
  demo_app:
    environment:
      - ALLOWED_HOSTS=demoapp.brayanperera.cyou
    image: demo_app:1.0
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /data/demo_app/db.sqlite3:/code/data/db.sqlite3
