---
- hosts: app_server
  tasks:
    - name: Create project Home
      file:
        path: /home/ec2-user/apps/demo_app
        state: directory
        mode: '0755'

    - name: Upload docker-compose.yaml
      copy:
        src: ../demo-app/docker-compose.yaml
        dest: /home/ec2-user/apps/demo_app/docker-compose.yaml
        mode: '0644'

    - name: ECR login
      shell: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 573847103844.dkr.ecr.ap-south-1.amazonaws.com/demo-app

    - name: Invoke docker-compose down
      command: docker-compose down
      args:
        chdir: /home/ec2-user/apps/demo_app/

    - name: Invoke docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user/apps/demo_app/

    - name: Run post deploy hooks
      shell: |
        sleep 10
        CONTAINER_ID=$(docker ps --filter="name=demo_app-demo_app" | awk '{print $1}' | grep -v CONTAINER | head -1)
        docker exec -it $CONTAINER_ID sh -c "bash /code/hooks/post_deploy_hook.sh"