AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ## VPC Parameters
  AzList:
    Type: CommaDelimitedList
    Default: "ap-southeast-1a, ap-southeast-1b"
  VpcCidrBlock:
    Type: String
    Default: 10.100.0.0/20
  PubCidrBlocks:
    Type: CommaDelimitedList
    Default: "10.100.1.0/24, 10.100.2.0/24"
  PvtCidrBlocks:
    Type: CommaDelimitedList
    Default: "10.100.11.0/24, 10.100.12.0/24"

  ## IAM Parameters
  IamUser:
    Type: String
    Default: infra_cli_user

  ## EC2 Parameters
  BastionHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Bastion Host instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "infra_provision"

  JenkinsHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Jenkins Host instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "infra_provision"

  AppHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Application Host instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "infra_provision"

  BastionInstanceType:
    Description: Bastion Host EC2 instance type
    Type: String
    Default: t3.small

  JenkinsInstanceType:
    Description: Jenkins Host EC2 instance type
    Type: String
    Default: t3.small

  AppInstanceType:
    Description: App Host EC2 instance type
    Type: String
    Default: t3.small

  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  BastionSSHLocation:
    Description: The IP address range that can be used to SSH to the Bastion EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.



Resources:

Metadata:

  Authors:
    Description:  Brayan Perera (brayan.perera@gmail.com)

  Purpose:
    Description: "This template creates deployment environment for Jenkins server and application servers"

  License: Apache-2.0

Outputs: